// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Hesaplar struct {
	ID              int64         `json:"id"`
	Iban            sql.NullInt64 `json:"iban"`
	HesapSahibiIsmi string        `json:"hesap_sahibi_ismi"`
	Bakiye          int64         `json:"bakiye"`
	ParaBirimi      string        `json:"para_birimi"`
	OlusturmaTarihi time.Time     `json:"olusturma_tarihi"`
}

type Kullanıcılar struct {
	KullanıcıAdı string `json:"kullanıcı_adı"`
	Şifre        string `json:"şifre"`
	Email        string `json:"email"`
}

type ParaTransferi struct {
	ID           int64 `json:"id"`
	GonderenIban int64 `json:"gonderen_iban"`
	AlanIban     int64 `json:"alan_iban"`
	// pozitif olmali
	Mikdar          int64     `json:"mikdar"`
	OlusturmaTarihi time.Time `json:"olusturma_tarihi"`
}

type Varlıklar struct {
	ID        int64 `json:"id"`
	HesapIban int64 `json:"hesap_iban"`
	// negatif ve pozitif olabilir
	Bakiye          int64     `json:"bakiye"`
	OlusturmaTarihi time.Time `json:"olusturma_tarihi"`
}
